version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm install
          wokring_directory: ./client
      - run:
          name: Running server tests
          command: npm test 
          working_directory: ./server
      - run:
          name: Running client tests
          command: npm test 
          working_directory: ./client
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Docker publish
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t szumied/node-react-cicd:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push szumied/node-react-cicd:$TAG
          working_directory: ./server
          
workflows:
    build-and-test:
      jobs:
        - build-and-test
